"""
email_service.py — Automated CSV Report Email Delivery via Resend
=================================================================
Enterprise Business Value:
    Automated weekly email reports delivered via the Resend transactional
    email API ensure that compliance officers, C-suite executives, and
    audit teams receive formatted HITL governance summaries without
    requiring dashboard access. This supports SOX/SOC2 compliance evidence
    trails and provides redundant delivery alongside Telegram reports.

    The Resend API was chosen for its developer-friendly interface,
    high deliverability rates, and native support for file attachments —
    ideal for programmatic CSV report delivery from Azure Functions.

Configuration:
    Set the following environment variable:
        RESEND_API_KEY=re_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    Obtain your API key from: https://resend.com/api-keys
"""
import os
import httpx
from typing import Optional
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_API_URL = "https://api.resend.com/emails"

# Default sender — must be a verified domain in Resend
RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", "HITL Gateway <reports@hitl-gateway.io>")


# ---------------------------------------------------------------------------
# Core: Send a simple CSV report via Resend
# ---------------------------------------------------------------------------
# Enterprise Business Value:
#   This function is the backbone of automated compliance reporting. It takes
#   a raw CSV string (generated by the weekly cron job), base64-encodes it,
#   and attaches it to a transactional email via the Resend API. This ensures
#   that audit teams receive machine-parseable data alongside a human-readable
#   summary — satisfying both regulatory and operational requirements.
# ---------------------------------------------------------------------------

async def send_simple_csv_report(
    csv_content: str,
    to_email: str,
    subject: Optional[str] = None,
    summary_html: Optional[str] = None,
) -> dict:
    """
    Send a CSV compliance report as an email attachment via the Resend API.

    Args:
        csv_content: Raw CSV string (e.g., from io.StringIO().getvalue()).
        to_email: Recipient email address.
        subject: Optional email subject line. Defaults to a timestamped report title.
        summary_html: Optional HTML body with a human-readable summary.
                      If not provided, a default summary is generated.

    Returns:
        A dict with 'success' (bool), 'message_id' (str or None), and 'error' (str or None).
    """
    if not RESEND_API_KEY:
        print("[EMAIL] RESEND_API_KEY not configured — report generated but not emailed")
        return {
            "success": False,
            "message_id": None,
            "error": "RESEND_API_KEY not configured",
        }

    # Generate default subject with timestamp
    now = datetime.now(timezone.utc)
    week_str = now.strftime("%Y-W%W")
    if not subject:
        subject = f"HITL Gateway — Weekly Compliance Report ({week_str})"

    # Generate default HTML summary if not provided
    if not summary_html:
        summary_html = (
            "<h2>HITL Gateway — Weekly Compliance Report</h2>"
            f"<p>Reporting period: Week {week_str}</p>"
            "<p>Please find the attached CSV report containing this week's "
            "HITL request audit trail, categorized by Status, Required Role, "
            "and average time-to-resolution.</p>"
            "<hr>"
            "<p><em>This report was auto-generated by the HITL Gateway "
            "Azure Timer Trigger (schedule: Friday 5:00 PM UTC).</em></p>"
            "<p><small>Do not reply to this email. For questions, contact "
            "your HITL Gateway administrator.</small></p>"
        )

    # Base64-encode the CSV content for the Resend attachment
    import base64
    csv_bytes = csv_content.encode("utf-8")
    csv_b64 = base64.b64encode(csv_bytes).decode("utf-8")
    filename = f"hitl_weekly_report_{week_str}.csv"

    # Build the Resend API payload
    payload = {
        "from": RESEND_FROM_EMAIL,
        "to": [to_email],
        "subject": subject,
        "html": summary_html,
        "attachments": [
            {
                "filename": filename,
                "content": csv_b64,
                "content_type": "text/csv",
            }
        ],
    }

    headers = {
        "Authorization": f"Bearer {RESEND_API_KEY}",
        "Content-Type": "application/json",
    }

    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                RESEND_API_URL,
                json=payload,
                headers=headers,
                timeout=15.0,
            )

            if resp.status_code in (200, 201):
                result = resp.json()
                message_id = result.get("id", "unknown")
                print(f"[EMAIL] Report sent to {to_email} — message_id={message_id}")
                return {
                    "success": True,
                    "message_id": message_id,
                    "error": None,
                }
            else:
                error_text = resp.text
                print(f"[EMAIL] Resend API error: {resp.status_code} — {error_text}")
                return {
                    "success": False,
                    "message_id": None,
                    "error": f"HTTP {resp.status_code}: {error_text}",
                }
    except Exception as exc:
        print(f"[EMAIL] Error sending report: {exc}")
        return {
            "success": False,
            "message_id": None,
            "error": str(exc),
        }
